### ISSUE TITLE
int2mac

### ISSUE THREAD

**Issue by RobertBergman** [josh73/migrate-host-reservations-to-kea-mysql#1]
int2mac doesn't handle mac addresses that end in 0 correctly.  After a bit of research found this solution to work properly:

    @staticmethod
    def int2mac(i):
        # ===========================================================================
        if type(i) == str:
            i = int(i, 16)
        s = ':'.join(['{}{}'.format(a, b)
                     for a, b
                     in zip(*[iter('{:012x}'.format(i))]*2)])
        return s

**Comment by josh73** [comment]
Hi Robert,

Thank you!
I will take a look over the weekend.

Josh

**Comment by josh73** [comment]
Hi Robert,

Yes, you are correct.
I agree that your solution works well.

It would be enough to replace strip() with replace. Something like this:
import re
def int2mac(i):
  #
===========================================================================
    if type(i) == str:
      i = int(i, 16)
    s = hex(i).replace('0x', '').zfill(12)
    s = re.sub(r'(..)(?=[^$])', r'\1:', s)
    return s

Another solution, using your zip and iter idea could be:
def int2mac3(i):
  #
===========================================================================
    if type(i) == str:
      i = int(i, 16)
    s = hex(i).replace('0x', '').zfill(12)
    t = zip(*[iter(s)]*2)
    u = ':'.join([(u+v) for u,v in t])
    return u

Thanks again!

Josh

**Comment by RobertBergman** [comment]
No problem.  I didn't want to just leave it there.  I'm using some of this
code to periodically update the database so it was important to be able to
compare mac addresses between the source data and the database.  If there
are 5000 hosts and you update the database once a minute, deleting all the
entries and re-adding them would exhaust the size of the index in short
order.  Also just replacing by searching for the mac was causing problems
because users would delete the original source entry and you'd be left with
host artifacts in the kea database.  when a new mac gets assigned to an ip,
you end up with two hosts with the same ip.   I don't think these were
issues with the original intent of the code which was to pull the hosts
from dhcpd.conf, but in the old system you could have duplicate macs with
different ip addresses which is fine, but duplicate ip addresses generates
an error when a host tries to get an ip and kea tries to read it from the
database.

**Comment by josh73** [comment]
Fixed in 2bbe7f94aefaa8f2cddff68d4f7c3349bc2592a3
